version: '3.1'

services:

  postgres:
    image: postgres:10
    container_name: my_postgres_container
    ports:
      - "5432:5432"  # Expose PostgreSQL on the default port
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - my_postgres_data:/var/lib/postgresql/data  # Persist data between container restarts

volumes:
  my_postgres_data: